version: '3.8'

services:
  # Serviço da API Flask
  api:
    build: .
    container_name: gameverse-api-service
    ports:
      - "3000:3000"
    volumes:
      # Monta o código local para hot-reload e o volume de dados para persistir o DB
      - .:/app
      - sqlite_data:/app/data
    environment:
      # A URL agora aponta para um arquivo SQLite dentro do volume de dados
      - DATABASE_URL=sqlite:////app/data/gameverse.db
      - SECRET_KEY=minha-chave-secreta-super-segura-do-compose
      - JWT_ALGORITHM=HS256

volumes:
  # Define o volume nomeado para persistência dos dados do SQLite
  sqlite_data: