version: '3.8'

services:
  api:
    build: .
    container_name: gameverse-api-service
    ports:
      - "3000:3000"
    volumes:
      # Monta o código local para hot-reload e o volume de dados para persistir o DB
      - .:/app
      - sqlite_data:/app/data
    env_file:
      - .env

# Declara o volume nomeado que será gerenciado pelo Docker
volumes:
  sqlite_data:
